export default {
  menu: {
    dashboard: "Dashboard",
    overview: "Overview",
    settings: "Settings",
    services: "Services",
    projects: "Projects",
    n8n: "N8N",
    databases: "Databases",
    messageQueues: "Message Queues",
    back: "Back to Project"
  },
  generic: {
    soon: "soon"
  },
  button: {
    save: "Save",
    cancel: "Cancel",
    newDatabase: "New database",
    delete: "Delete Service"
  },
  service: {
    detailsTitle: "Service Details",
    addTitle: "Service Creation",
    editTitle: "Service Edit",
    serviceType: "Service type",
    storageSize: "Storage size",
    name: "Name",
    namePlaceholder: "Will be autogenerated if left blank",
    description: "Description",
    type: "Type",
    host: "Host",
    database: "Database",
    user: "User",
    password: "Password",
    createdAt: "Created",
    createdBy: "Creator",
    parametersOnly: "Parameters only"
  },
  project: {
    addTitle: "Project Creation",
    editTitle: "Project Edit",
    name: "Name",
    namePlaceholder: "Will be autogenerated if left blank",
    description: "Description",
    settings: {
      title: "Settings",
      general: {
        title: "General"
      },
      delete: {
        title: "Delete Project"
      },
      compute: "Compute"
    },
    database: {
      title: "Databases",
      table: {
        name: "Name",
        serviceType: "Service Type",
        storageSize: "Storage Size",
        createdAt: "Created",
        createdBy: "Creator"
      }
    }
  },
  projects: {
    services: "services"
  }
};